services:
  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    volumes:
      - ./jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
    network_mode: host
  
  sftpgo:
    image: drakkan/sftpgo
    container_name: sftpgo
    volumes:
      - ./sftpgo/data:/srv/sftpgo
      - ./sftpgo/home:/var/lib/sftpgo
      - /mnt:/usb
    ports:
      - 8080:8080
      - 2022:2022
    restart: unless-stopped